stages:
- build

build:
  stage: build
  image: python:3
  script:
    - python -V
    - ./build.sh -v
  artifacts:
    paths:
      - build/
    expire_in: 1 hr
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: on_success
    - when: manual
